// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": ["http"],
    "swagger": "2.0",
    "info": {
        "description": "Multi-OLT SNMP monitoring system for ZTE devices",
        "title": "SNMP-ZTE API",
        "contact": {"name": "ardani17", "email": "adifta22@gmail.com"},
        "license": {"name": "MIT"},
        "version": "2.1"
    },
    "host": "localhost:8080",
    "basePath": "/",
    "paths": {
        "/api/v1/query": {
            "post": {
                "description": "Query OLT data without storing credentials",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "summary": "Stateless SNMP Query",
                "tags": ["Query"],
                "parameters": [{"name": "body", "in": "body", "required": true, "schema": {"type": "object", "required": ["ip", "community", "query"], "properties": {"ip": {"type": "string"}, "port": {"type": "integer"}, "community": {"type": "string"}, "model": {"type": "string"}, "query": {"type": "string"}, "board": {"type": "integer"}, "pon": {"type": "integer"}, "onu_id": {"type": "integer"}}}}],
                "responses": {"200": {"description": "OK"}, "400": {"description": "Bad Request"}, "500": {"description": "Internal Server Error"}}
            }
        },
        "/api/v1/olt-info": {
            "post": {
                "description": "Get OLT system information",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "summary": "Get OLT System Info",
                "tags": ["Query"],
                "parameters": [{"name": "body", "in": "body", "required": true, "schema": {"type": "object", "required": ["ip"], "properties": {"ip": {"type": "string"}, "port": {"type": "integer"}, "community": {"type": "string"}, "model": {"type": "string"}}}}],
                "responses": {"200": {"description": "OK"}, "400": {"description": "Bad Request"}, "500": {"description": "Internal Server Error"}}
            }
        },
        "/health": {
            "get": {"description": "Health check endpoint", "produces": ["application/json"], "summary": "Health Check", "tags": ["System"], "responses": {"200": {"description": "OK"}}}
        },
        "/stats": {
            "get": {"description": "Get SNMP connection pool statistics", "produces": ["application/json"], "summary": "Pool Statistics", "tags": ["System"], "responses": {"200": {"description": "OK"}}}
        }
    }
}`

// SwaggerInfo holds swagger info
var SwaggerInfo = &swag.Spec{
	Version:          "2.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "SNMP-ZTE API",
	Description:      "Multi-OLT SNMP monitoring system for ZTE devices",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
